### ISSUE TITLE
C++ templates are Turing complete

### ISSUE THREAD

**Issue by SamChou19815** [khemritolya/libbrain#1]
This repo is a nice attempt to prove [it](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.14.3670&rep=rep1&type=pdf).

**Comment by khemritolya** [comment]
While true, what this repo has really proven is that g++ can be ~~used~~ forced to compile languages which are not c or c++. Also, we can embed (theoretically at least) every other language inside c++, which shows that g++ really is a universal compiler.
